### ISSUE TITLE
error  when  start vim

### ISSUE THREAD

**Issue by smartegg** [amoffat/snake#11]
![image](https://cloud.githubusercontent.com/assets/1090467/7726507/38f17cde-ff35-11e4-96fe-5621b9c12477.png)

my python version is `2.6.6`

**Comment by amoffat** [comment]
Yeah, it's that syntax.  I don't have a Vim compiled against Python 2.6, but I can fix the syntax.  I don't know what else will break though.  Could you output `vim --version` please?

**Comment by smartegg** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 15 2015 04:40:09)
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    
+farsi           +mouse_netterm   +syntax

**Comment by smartegg** [comment]
I  guess this  Syntactic sugar is not  support in  python 2.6 ?    :)

**Comment by amoffat** [comment]
@smartegg sorry about the delay.  go ahead and pull master and let me know if that works.  i don't know what else will break though

**Comment by smartegg** [comment]
It  works  now!  :)  
Thanks!
