### ISSUE TITLE
How can I insert an code snippet in file?  

### ISSUE THREAD

**Issue by ZCT** [amoffat/snake#13]
for example i map this to insert an code snippet:
   @key_map("<leader>coco")
    def cocoCreate():
    #in this function how insert code in File?

**Comment by amoffat** [comment]
sorry for the late reply on this!  somehow i missed it.

i think you want to do something like this:

```python
@key_map("<leader>o")
def cocoCreate():
    with preserve_registers("a"):
        set_register("a", "testing")
        keys('"ap')
```

**Comment by ZCT** [comment]
yeap, thks~~~
sorry for the late reply :+1:
