### ISSUE TITLE
Tests hang on my machine

### ISSUE THREAD

**Issue by averagehat** [amoffat/snake#18]
vim version 7.4 
sh is installed 

``` bash
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

output:

https://gist.github.com/averagehat/32afe838aff91af2d5c3

**Comment by amoffat** [comment]
I've had this happen a few times.  It usually had to do with vim printing an error message and then expecting you to press enter.  Try uncommenting this line https://github.com/amoffat/snake/blob/master/tests.py#L69 and see if any error message gets printed out before it hangs.
