### ISSUE TITLE
Python 3 scripting?

### ISSUE THREAD

**Issue by intelfx** [amoffat/snake#20]
it would be nice to have a knob to make snake use python 3 engine, or at least a separate branch with python 3 support (as in intelfx/snake@0085142d6d0df7e13848cc72f63bd5ff8dcf47fe).

Or, even better, make it use python 3 by default (sweet dreams of a legacy-free world).

**Comment by amoffat** [comment]
Python2 and Python3 are now both supported

**Comment by intelfx** [comment]
@amoffat Can we at least have a choice which python to use? py3 as a fallback only is really not nice.
