### ISSUE TITLE
1337 stars!

### ISSUE THREAD

**Issue by reimertz** [amoffat/snake#23]
Ok, so I created  [1337repos](https://reimertz.github.io/1337repos) and randomly visited it today. 

I saw `snake` and I guess deep down I wished it was related to Metal Gear. I was not disappointed. 

The gif, the jokes, the references, everything! 

Good work and good luck with this awesome tool. I hope you all the best.

_also, sorry for spam/non-issue_

**Comment by amoffat** [comment]
Thanks!  1337repos is fun, cheers!
